spring.application.name=estoque

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/adega_estoque
spring.datasource.username=adega
spring.datasource.password=adega_dev

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true